# Generated by Django 4.0.5 on 2022-06-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=10, verbose_name='Наименование банка')),
                ('term_min', models.PositiveIntegerField(verbose_name='Срок ипотеки, ОТ')),
                ('term_max', models.PositiveIntegerField(verbose_name='Срок ипотеки, ДО')),
                ('rate_min', models.FloatField(verbose_name='Ставка, ОТ')),
                ('rate_max', models.FloatField(verbose_name='Ставка, ДО')),
                ('payment_min', models.PositiveIntegerField(verbose_name='Сумма кредита, ОТ')),
                ('payment_max', models.PositiveIntegerField(verbose_name='Сумма кредита, ДО')),
            ],
            options={
                'verbose_name': 'Ипотечное предложение',
                'verbose_name_plural': 'Ипотечные предложения',
            },
        ),
    ]
